project:
  type: website
  output-dir: docs

website:
  title: "avinash13808138.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: Avinash_Singh_Resume.pdf
        text: Resume
      - text: Assignments
        menu:
          - href: epps6302_assignment01.pdf
            text: "Assignment 1 - Instructions"
          - href: assign01.qmd
            text: "Assignment 1 - Website Design Note"
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

