project:
  type: website
  output-dir: docs
  resources:
    - Avinash_Singh_Resume.pdf
    - epps6302_assignment01.pdf
    - epps6302_assignment02.pdf
    - epps6302_assignment03.pdf
    - epps6302_assignment04.pdfqu

website:
  title: "avinash13808138.github.io"

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: Avinash_Singh_Resume.pdf
        text: Resume
      - text: Assignments
        menu:
          - href: epps6302_assignment01.pdf
            text: "Assignment 1 - Instructions"

          - href: assign01.qmd
            text: "Assignment 1 - Website Design Note"

          - href: epps6302_assignment02.pdf
            text: "Assignment 2 - Instructions"

          - href: Assignment_2_Notes.qmd
            text: "Assignment 2 - Notes"

          - href: assign02.qmd
            text: "Assignment 2 - Google Trends Analysis"
            
          - href: epps6302_assignment03.pdf
            text: "Assignment 3 - Instructions"

          - href: Assignment 3.qmd
            text: "Assignment 3 - ACS via tidycensus"
            
          - href: epps6302_assignment04.pdf
            text: "epps6302_assignment04 - Instructions"
            
          - href: Assignment 04_Data Plan.qmd
            text: "Assignment 04_Data Plan"
            
          - href: Assignment04.qmd
            text: "Assignment04"   
            

# Apply these execution settings to all .qmd pages
execute:
  warning: false
  message: false

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual