project:
  type: website
  output-dir: docs
  resources:
    - Avinash_Singh_Resume.pdf
    - epps6302_assignment01.pdf
    - epps6302_assignment02.pdf
    
    

website:
  title: "avinash13808138.github.io"
  
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: Avinash_Singh_Resume.pdf
        text: Resume
      - text: Assignments
        menu:
          - href: epps6302_assignment01.pdf
            text: "Assignment 1 - Instructions"
            
          - href: assign01.qmd
            text: "Assignment 1 - Website Design Note"
            
          - href: epps6302_assignment02.pdf
            text: "Assignment 2 - Instructions"

          - href: Assignment_2_Notes.qmd
            text: "Assignment 2 - Notes (Word)"

          - href: assign02.qmd
            text: "Assignment 2 - Google Trends Analysis"
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

